Update to API
salesagility/SuiteDocs pull request #512
Opened 2021-05-19 13:11 UTC by jack7anderson7

Update to the JSON and Portal Page

2021-05-19 13:15 UTC, simonr44 approved these changes

2021-05-19 13:15 UTC, simonr44 approved these changes

2021-05-19 13:16 UTC, Dillon-Brown requested changes

2021-05-19 13:16 UTC, Dillon-Brown commented on content/developer/api/Developer-setup-guide/JSON-API.adoc
> +const OAUTH2_ENCRYPTION_KEY = '{Encryption Key}';
This doesn't seem right, we shouldn't be asking people to make core changes in order to get the API working. This value should be coming from the ```oauth2_encryption_key``` in the config. I can't seem to find anywhere that would even use this constant either.

2021-05-19 14:15 UTC, Dillon-Brown approved these changes

2021-05-19 14:17 UTC, simonr44 approved these changes

2021-05-19 14:23 UTC, mattlorimer requested changes

2021-05-19 14:23 UTC, mattlorimer commented on content/user/advanced-modules/Cases with Portal.adoc
> +for the V8 API. This can be done here:
The Joomla portal currently still uses the V4 API so not sure if this is specifically required for that

2021-05-19 14:23 UTC, mattlorimer commented on content/user/advanced-modules/Cases with Portal.adoc
> +Joomla URL,when configuring the Joomla URL be sure to use your local network IP instead of localhost or 127.0.0.1,
this specific to networking with docker when working locally I assume and so may need to be more specific whats being refereed to here

2021-05-26 12:56 UTC, mattlorimer approved these changes

2021-05-26 12:56 UTC, merged